name: "Gitops deploy"

on:
  push:
    branches: [ deploy-demo ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }} # `PAT` is a secret that contains your Personal Access Token with `write:packages` scope

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}

    - name: Checkout GitOps repo
      uses: actions/checkout@v2
      with:
        repository: laszlocph/gitops-fleet
        token: ${{ secrets.PAT }} # `PAT` is a secret that contains your Personal Access Token with `repo` scope
        path: gitops

    - name: Write to GitOps repository
      run: |
        mkdir templated-manifests
        cat manifests/deployment.yaml | envsubst > templated-manifests/deployment.yaml
        cat manifests/service.yaml | envsubst > templated-manifests/service.yaml
        
        cp -r templated-manifests/ gitops/clusters/civo-workshop/$GITHUB_REPOSITORY_NAME-app

        (cd gitops/; git commit -m "Deploying $GITHUB_SHA")
        (cd gitops/; git push origin main)
      env:
        GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
